# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 672)
        MainWindow.setStyleSheet("QWidget{\n"
"    color: white;\n"
"    background-color:rgb(25, 35, 45);\n"
"    border: 1px solid rgb(69, 83, 100);\n"
"}\n"
"\n"
"QLabel{\n"
"    border: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(69, 83, 100);\n"
"    border-radius: 4px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(84, 104, 122);\n"
"    border-radius: 4px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QMainWindow > QWidget > QPushButton[text=\"Start\"]{\n"
"    background-color:rgb(104, 149, 102);\n"
"    min-width: 80px;\n"
"    max-width: 80px;\n"
"    min-height: 80px;\n"
"    max-height: 80px;\n"
"    border-radius: 40px;\n"
"}\n"
"\n"
"QMainWindow > QWidget > QPushButton[text=\"Stop\"]{\n"
"    background-color: rgb(181, 74, 74);\n"
"    min-width: 80px;\n"
"    max-width: 80px;\n"
"    min-height: 80px;\n"
"    max-height: 80px;\n"
"    border-radius: 40px;\n"
"}\n"
"\n"
"QTabWidget::pane{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar{\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar{\n"
"    border: 0;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(69, 83, 100);\n"
"    border: 0;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"    min-width: 10ex;\n"
"    min-height: 5ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:selected:hover{\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.5, x2:0.5, y2:1, stop:0.681818 rgba(84, 104, 122, 255), stop:0.7 rgba(52, 64, 216, 255));\n"
"    margin-bottom: 0;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(84, 104, 122);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar{\n"
"    border: 0;\n"
"    background: rgb(69, 83, 100);\n"
"    height: 3ex;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: rgb(84, 104, 122);\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(84, 104, 122);\n"
"    selection-background-color: rgb(84, 104, 122);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(84, 104, 122);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid rgb(84, 104, 122);\n"
"    border-radius: 4px;\n"
"    background-color: rgb(84, 104, 122);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right;\n"
"    min-width: 24px;\n"
"    border-left-width: 1px;\n"
"    border-left-color:rgb(69, 83, 100);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/arrow-down-outline.svg);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid rgb(69, 83, 100);\n"
"    selection-background-color: rgb(84, 104, 122);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    selection-background-color: rgb(84, 104, 122);\n"
"}\n"
"\n"
"\n"
"QWidget:disabled{\n"
"    color: rgb(85, 104, 124);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background-color: rgb(34, 41, 49);\n"
"}\n"
"\n"
"QLineEdit:disabled{\n"
"    background-color: rgb(34, 41, 49);\n"
"}\n"
"\n"
"QComboBox:disabled{\n"
"    background-color: rgb(34, 41, 49);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_start_stop = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start_stop.setMinimumSize(QtCore.QSize(80, 80))
        self.bt_start_stop.setMaximumSize(QtCore.QSize(80, 80))
        self.bt_start_stop.setStyleSheet("")
        self.bt_start_stop.setObjectName("bt_start_stop")
        self.horizontalLayout_3.addWidget(self.bt_start_stop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(855, 550))
        self.tabWidget.setObjectName("tabWidget")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.config_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(213, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_file_regex = QtWidgets.QLabel(self.config_tab)
        self.lb_file_regex.setEnabled(True)
        self.lb_file_regex.setObjectName("lb_file_regex")
        self.horizontalLayout_5.addWidget(self.lb_file_regex)
        self.le_file_regex = QtWidgets.QLineEdit(self.config_tab)
        self.le_file_regex.setAlignment(QtCore.Qt.AlignCenter)
        self.le_file_regex.setObjectName("le_file_regex")
        self.horizontalLayout_5.addWidget(self.le_file_regex)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_period = QtWidgets.QLabel(self.config_tab)
        self.lb_period.setObjectName("lb_period")
        self.horizontalLayout.addWidget(self.lb_period)
        self.le_period = QtWidgets.QLineEdit(self.config_tab)
        self.le_period.setEnabled(True)
        self.le_period.setAlignment(QtCore.Qt.AlignCenter)
        self.le_period.setObjectName("le_period")
        self.horizontalLayout.addWidget(self.le_period)
        self.cb_period_unit = QtWidgets.QComboBox(self.config_tab)
        self.cb_period_unit.setEnabled(True)
        self.cb_period_unit.setMinimumSize(QtCore.QSize(120, 0))
        self.cb_period_unit.setObjectName("cb_period_unit")
        self.cb_period_unit.addItem("")
        self.cb_period_unit.addItem("")
        self.cb_period_unit.addItem("")
        self.horizontalLayout.addWidget(self.cb_period_unit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_source_dir = QtWidgets.QLabel(self.config_tab)
        self.lb_source_dir.setObjectName("lb_source_dir")
        self.gridLayout_2.addWidget(self.lb_source_dir, 0, 0, 1, 1)
        self.bt_set_src_dir = QtWidgets.QPushButton(self.config_tab)
        self.bt_set_src_dir.setObjectName("bt_set_src_dir")
        self.gridLayout_2.addWidget(self.bt_set_src_dir, 0, 1, 1, 1)
        self.lb_destination_dir = QtWidgets.QLabel(self.config_tab)
        self.lb_destination_dir.setObjectName("lb_destination_dir")
        self.gridLayout_2.addWidget(self.lb_destination_dir, 5, 0, 1, 1)
        self.bt_set_dest_dir = QtWidgets.QPushButton(self.config_tab)
        self.bt_set_dest_dir.setObjectName("bt_set_dest_dir")
        self.gridLayout_2.addWidget(self.bt_set_dest_dir, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.bt_swap_src_dst = QtWidgets.QPushButton(self.config_tab)
        self.bt_swap_src_dst.setMinimumSize(QtCore.QSize(60, 0))
        self.bt_swap_src_dst.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bt_swap_src_dst.setObjectName("bt_swap_src_dst")
        self.horizontalLayout_2.addWidget(self.bt_swap_src_dst)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(213, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 2, 1, 1, 1)
        self.tabWidget.addTab(self.config_tab, "")
        self.charts_tab = QtWidgets.QWidget()
        self.charts_tab.setObjectName("charts_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.charts_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.charts_tab, "")
        self.logging_tab = QtWidgets.QWidget()
        self.logging_tab.setObjectName("logging_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logging_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.logging_tab)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.logging_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Periodic File Transfer"))
        self.bt_start_stop.setText(_translate("MainWindow", "Start"))
        self.lb_file_regex.setText(_translate("MainWindow", "Expression to be matched:"))
        self.lb_period.setText(_translate("MainWindow", "Period:"))
        self.cb_period_unit.setItemText(0, _translate("MainWindow", "Seconds"))
        self.cb_period_unit.setItemText(1, _translate("MainWindow", "Minutes"))
        self.cb_period_unit.setItemText(2, _translate("MainWindow", "Hours"))
        self.lb_source_dir.setText(_translate("MainWindow", "path/to/source/folder"))
        self.bt_set_src_dir.setText(_translate("MainWindow", "Select Source Folder"))
        self.lb_destination_dir.setText(_translate("MainWindow", "path/to/destination/folder"))
        self.bt_set_dest_dir.setText(_translate("MainWindow", "Select Destination Folder"))
        self.bt_swap_src_dst.setText(_translate("MainWindow", "Swap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), _translate("MainWindow", "Configurations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.charts_tab), _translate("MainWindow", "Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logging_tab), _translate("MainWindow", "Logs"))
import styleresources_rc
